apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag2-apr29-1-app-tekton
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/rag2-apr29-1/overlays/tekton
    repoURL: https://github.com/redhat-appstudio-mjf/rag2-apr29-1-gitops.git
    targetRevision: main
  destination:
    namespace: rag2-apr29-1
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: ai-rhdh
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
