apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: rag2-apr29-1
  janus-idp.io/tekton: rag2-apr29-1
  backstage.io/kubernetes-id: rag2-apr29-1
  backstage.io/kubernetes-namespace: rag2-apr29-1
  app.kubernetes.io/part-of: rag2-apr29-1
resources:
  - application-dev.yaml